language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libogg-dev
    - libmpeg2-4-dev

before_install:
  # download a static-built ffmpeg from the official website
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - tar -xf ffmpeg-release-64bit-static.tar.xz
  - sudo cp ffmpeg-3.4.1-64bit-static/ffmpeg /usr/bin/
  - sudo cp ffmpeg-3.4.1-64bit-static/ffprobe /usr/bin/

install:
  # upgrade gcc
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  # verify installed versions
  - g++ -v
  - ffmpeg -version

script:
  - ./autogen.sh
  - ./configure
  - make -j3 distcheck V=1 || (cat tv-encoder-0.1/_build/src/tests/test-suite.log && exit 1)

notifications:
  email: false
  webhooks:
    - https://snr.zulipchat.com/api/v1/external/travis?api_key=3GNy11c5XW50JIfv6Ap07h5ZHMQN4Rb5&stream=tv-notification&topic=build-status
